[env]
TERM="xterm-256color"
LANG="en_US"
LANGUAGE="en_US:en"
LC_ALL="en_US.UTF-8"
LC_TERMINAL="Alacritty"

[font]
size=12.0
normal={family="Hack Nerd Font Propo", style="Regular"}
bold={family="Hack Nerd Font Propo", style="Bold"}
italic={family="Hack Nerd Font Propo", style="Italic"}
bold_italic={family="Hack Nerd Font Propo", style="Bold Italic"}

[colors]
draw_bold_text_with_bright_colors=true

[terminal]
shell={program="/bin/zsh", args=["-l"]}

[selection]
save_to_clipboard=true

[mouse]
hide_when_typing=true

[window]
opacity=0.8
blur=true

[general]
import = ["./dracula.toml"]

# [keyboard]
# bindings=[ {key="Return", mods="Super|Shift", action="SpawnNewInstance"} ]
